### ISSUE TITLE
[1.20.1 NEOFORGE] JEI Crash with latest Glodium and ExtendedAE (Crash on World Load)

### ISSUE THREAD

**Issue by Zedrimar** [GlodBlock/Glodium#3]
ExtendedAE: 1.20-1.0.18
Neoforge: 47.1.103
Glodium: 1.20-1.4
JEI: 1.20.1-forge-15.3.0.4

Game loads, but crashes on world load. Removing JEI or reverting Glodium to 1.3 stops the crashes from happening. Also tried on a new world just in case my current one was now incompatible, though sadly had the same result.

Crash from main modded setup:
https://mclo.gs/v9hEtVG

Crash from test setup:
https://mclo.gs/zNyLcmx

Both crash reports basically show the same thing, but the test setup one is shorter.

**Comment by Zedrimar** [comment]
Issue still persists with ExtendedAE 1.20-1.0.19

Just for the hell of it, I also tested with Glodium 1.4 and JEI just by itself. Those load just fine, and world will load. Seems like the changes just weren't adapted to on ExtendedAE, with the new reflect lib.

**Comment by GlodBlock** [comment]
downgrade to 1.3 or use java17 because java17+ will crash with 1.4
i will push 1.5 soon and it will fix the crash with java17+

**Comment by Zedrimar** [comment]
Sorry it took so long to reply. Never thought having too new of a Java version would be the thing to do it. Good to know. If you don't mind me asking, Just curious if you know what it was specifically between Java 17 and the newer versions that caused the crash? I want to try and avoid it for my own mod development ventures.

Also, thanks for the fix, much appreciated! ^-^
