### ISSUE TITLE
有严重问题

### ISSUE THREAD

**Issue by krzj** [GlodBlock/Glodium#5]
无法开始

**Comment by GlodBlock** [comment]
请提供错误报告和mod版本

**Comment by krzj** [comment]
[Uploading minecraft-exported-crash-info-2024-08-01T15-03-44.zip…]()

**Comment by krzj** [comment]
[minecraft-exported-crash-info-2024-08-01T15-03-44.zip](https://github.com/user-attachments/files/16451572/minecraft-exported-crash-info-2024-08-01T15-03-44.zip)

**Comment by GlodBlock** [comment]
看起来像oculus导致的，日志里没有和glodium相关的内容

**Comment by krzj** [comment]
> 看起来像oculus导致的，日志里没有和glodium相关的内容

hmcl ,pcl  都指向glodium

**Comment by GlodBlock** [comment]
那你把glodium和ExtendedAE下了能启动吗

**Comment by krzj** [comment]
> 那你把glodium和ExtendedAE下了能启动吗

可以的，所以才来找你

**Comment by GlodBlock** [comment]
是植物魔法的问题，那里有人遇到和你一样的问题https://github.com/VazkiiMods/Botania/issues/4733
植物魔法那边已经在修了
